surface.CreateFont("DarkRPHUD1", {size = 20,weight = 600,shadow = true,font = "Roboto"})
surface.CreateFont("DarkRPHUD2", {size = 23,weight = 400,font = "Roboto"})
surface.CreateFont("Roboto20", {size = 20,weight = 600,font = "Roboto"})
surface.CreateFont("TabLarge", {size = 18,weight = 700,font = "Roboto"})
surface.CreateFont("UiBold", {size = 16,weight = 800,font = "Verdana"})
